// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD19jgPRIEbkWbS6MLgryRC3TRtapNlr-I',
    appId: '1:40214011444:web:6cf079c8e06761b0f57461',
    messagingSenderId: '40214011444',
    projectId: 'iti-proj-85b43',
    authDomain: 'iti-proj-85b43.firebaseapp.com',
    storageBucket: 'iti-proj-85b43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiQOBj8RCMxfNDYhIyI5z4WO9zoCpNKQo',
    appId: '1:40214011444:android:5779ff71afd1ca51f57461',
    messagingSenderId: '40214011444',
    projectId: 'iti-proj-85b43',
    storageBucket: 'iti-proj-85b43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi2T8RTcjhxh5hh5lQpFjX3BVfzj6_K8g',
    appId: '1:40214011444:ios:dc4e81881ed15f6df57461',
    messagingSenderId: '40214011444',
    projectId: 'iti-proj-85b43',
    storageBucket: 'iti-proj-85b43.appspot.com',
    iosBundleId: 'com.example.projIti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi2T8RTcjhxh5hh5lQpFjX3BVfzj6_K8g',
    appId: '1:40214011444:ios:dc4e81881ed15f6df57461',
    messagingSenderId: '40214011444',
    projectId: 'iti-proj-85b43',
    storageBucket: 'iti-proj-85b43.appspot.com',
    iosBundleId: 'com.example.projIti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD19jgPRIEbkWbS6MLgryRC3TRtapNlr-I',
    appId: '1:40214011444:web:a19102b736c95298f57461',
    messagingSenderId: '40214011444',
    projectId: 'iti-proj-85b43',
    authDomain: 'iti-proj-85b43.firebaseapp.com',
    storageBucket: 'iti-proj-85b43.appspot.com',
  );
}
